/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sokoban;

import static sokoban.Sokoban.player_level;
import static sokoban.Sokoban.level;
import static sokoban.Sokoban.inter;
import static sokoban.Sokoban.counter_win;
import static sokoban.homeForm.qui;
import static sokoban.Sokoban.levels_open;

/**
 *
 * @author Win10
 */
public class hardMenu extends javax.swing.JFrame {
    
     
    /* public void setplayer_level(int playerLevel){
         this.player_level=playerLevel;
     }
     */
     public int getplayer_level(){
         return player_level;
     }
    /**
     * Creates new form hardMenu
     */
    public hardMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        hardPanel = new javax.swing.JPanel();
        jButton41 = new javax.swing.JButton();
        jButton42 = new javax.swing.JButton();
        jButton43 = new javax.swing.JButton();
        jButton44 = new javax.swing.JButton();
        jButton45 = new javax.swing.JButton();
        jButton46 = new javax.swing.JButton();
        jButton47 = new javax.swing.JButton();
        jButton48 = new javax.swing.JButton();
        jButton49 = new javax.swing.JButton();
        jButton50 = new javax.swing.JButton();
        jButton51 = new javax.swing.JButton();
        jButton52 = new javax.swing.JButton();
        jButton53 = new javax.swing.JButton();
        jButton54 = new javax.swing.JButton();
        jButton55 = new javax.swing.JButton();
        jButton56 = new javax.swing.JButton();
        jButton57 = new javax.swing.JButton();
        jButton58 = new javax.swing.JButton();
        jButton59 = new javax.swing.JButton();
        jButton60 = new javax.swing.JButton();
        backBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("hardMenu");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        hardPanel.setBackground(new java.awt.Color(0, 153, 225));
        hardPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton41.setBackground(new java.awt.Color(255, 102, 0));
        jButton41.setFont(new java.awt.Font("Traditional Arabic", 1, 36)); // NOI18N
        jButton41.setForeground(new java.awt.Color(255, 255, 255));
        jButton41.setText("41");
        jButton41.setFocusable(false);
        jButton41.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jButton41AncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jButton41.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton41ActionPerformed(evt);
            }
        });
        hardPanel.add(jButton41, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 100, 100, 100));

        jButton42.setBackground(new java.awt.Color(255, 102, 0));
        jButton42.setFont(new java.awt.Font("Traditional Arabic", 1, 36)); // NOI18N
        jButton42.setForeground(new java.awt.Color(255, 255, 255));
        jButton42.setText("42");
        jButton42.setToolTipText("");
        jButton42.setFocusPainted(false);
        jButton42.setFocusable(false);
        jButton42.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jButton42AncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jButton42.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton42ActionPerformed(evt);
            }
        });
        hardPanel.add(jButton42, new org.netbeans.lib.awtextra.AbsoluteConstraints(265, 100, 100, 100));

        jButton43.setBackground(new java.awt.Color(255, 102, 0));
        jButton43.setFont(new java.awt.Font("Traditional Arabic", 1, 36)); // NOI18N
        jButton43.setForeground(new java.awt.Color(255, 255, 255));
        jButton43.setText("43");
        jButton43.setFocusPainted(false);
        jButton43.setFocusable(false);
        jButton43.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jButton43AncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jButton43.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton43ActionPerformed(evt);
            }
        });
        hardPanel.add(jButton43, new org.netbeans.lib.awtextra.AbsoluteConstraints(415, 100, 100, 100));

        jButton44.setBackground(new java.awt.Color(255, 102, 0));
        jButton44.setFont(new java.awt.Font("Traditional Arabic", 1, 36)); // NOI18N
        jButton44.setForeground(new java.awt.Color(255, 255, 255));
        jButton44.setText("44");
        jButton44.setFocusPainted(false);
        jButton44.setFocusable(false);
        jButton44.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jButton44AncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jButton44.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton44ActionPerformed(evt);
            }
        });
        hardPanel.add(jButton44, new org.netbeans.lib.awtextra.AbsoluteConstraints(565, 100, 100, 100));

        jButton45.setBackground(new java.awt.Color(255, 102, 0));
        jButton45.setFont(new java.awt.Font("Traditional Arabic", 1, 36)); // NOI18N
        jButton45.setForeground(new java.awt.Color(255, 255, 255));
        jButton45.setText("45");
        jButton45.setFocusPainted(false);
        jButton45.setFocusable(false);
        jButton45.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jButton45AncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jButton45.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton45ActionPerformed(evt);
            }
        });
        hardPanel.add(jButton45, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 225, 100, 100));

        jButton46.setBackground(new java.awt.Color(255, 102, 0));
        jButton46.setFont(new java.awt.Font("Traditional Arabic", 1, 36)); // NOI18N
        jButton46.setForeground(new java.awt.Color(255, 255, 255));
        jButton46.setText("46");
        jButton46.setFocusPainted(false);
        jButton46.setFocusable(false);
        jButton46.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jButton46AncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jButton46.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton46ActionPerformed(evt);
            }
        });
        hardPanel.add(jButton46, new org.netbeans.lib.awtextra.AbsoluteConstraints(265, 225, 100, 100));

        jButton47.setBackground(new java.awt.Color(255, 102, 0));
        jButton47.setFont(new java.awt.Font("Traditional Arabic", 1, 36)); // NOI18N
        jButton47.setForeground(new java.awt.Color(255, 255, 255));
        jButton47.setText("47");
        jButton47.setFocusPainted(false);
        jButton47.setFocusable(false);
        jButton47.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jButton47AncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jButton47.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton47ActionPerformed(evt);
            }
        });
        hardPanel.add(jButton47, new org.netbeans.lib.awtextra.AbsoluteConstraints(415, 225, 100, 100));

        jButton48.setBackground(new java.awt.Color(255, 102, 0));
        jButton48.setFont(new java.awt.Font("Traditional Arabic", 1, 36)); // NOI18N
        jButton48.setForeground(new java.awt.Color(255, 255, 255));
        jButton48.setText("48");
        jButton48.setFocusPainted(false);
        jButton48.setFocusable(false);
        jButton48.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jButton48AncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jButton48.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton48ActionPerformed(evt);
            }
        });
        hardPanel.add(jButton48, new org.netbeans.lib.awtextra.AbsoluteConstraints(565, 225, 100, 100));

        jButton49.setBackground(new java.awt.Color(255, 102, 0));
        jButton49.setFont(new java.awt.Font("Traditional Arabic", 1, 36)); // NOI18N
        jButton49.setForeground(new java.awt.Color(255, 255, 255));
        jButton49.setText("49");
        jButton49.setFocusPainted(false);
        jButton49.setFocusable(false);
        jButton49.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jButton49AncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jButton49.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton49ActionPerformed(evt);
            }
        });
        hardPanel.add(jButton49, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 350, 100, 100));

        jButton50.setBackground(new java.awt.Color(255, 102, 0));
        jButton50.setFont(new java.awt.Font("Traditional Arabic", 1, 36)); // NOI18N
        jButton50.setForeground(new java.awt.Color(255, 255, 255));
        jButton50.setText("50");
        jButton50.setFocusPainted(false);
        jButton50.setFocusable(false);
        jButton50.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jButton50AncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jButton50.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton50ActionPerformed(evt);
            }
        });
        hardPanel.add(jButton50, new org.netbeans.lib.awtextra.AbsoluteConstraints(265, 350, 100, 100));

        jButton51.setBackground(new java.awt.Color(255, 102, 0));
        jButton51.setFont(new java.awt.Font("Traditional Arabic", 1, 36)); // NOI18N
        jButton51.setForeground(new java.awt.Color(255, 255, 255));
        jButton51.setText("51");
        jButton51.setFocusPainted(false);
        jButton51.setFocusable(false);
        jButton51.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jButton51AncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jButton51.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton51ActionPerformed(evt);
            }
        });
        hardPanel.add(jButton51, new org.netbeans.lib.awtextra.AbsoluteConstraints(415, 350, 100, 100));

        jButton52.setBackground(new java.awt.Color(255, 102, 0));
        jButton52.setFont(new java.awt.Font("Traditional Arabic", 1, 36)); // NOI18N
        jButton52.setForeground(new java.awt.Color(255, 255, 255));
        jButton52.setText("52");
        jButton52.setFocusPainted(false);
        jButton52.setFocusable(false);
        jButton52.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jButton52AncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jButton52.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton52ActionPerformed(evt);
            }
        });
        hardPanel.add(jButton52, new org.netbeans.lib.awtextra.AbsoluteConstraints(565, 350, 100, 100));

        jButton53.setBackground(new java.awt.Color(255, 102, 0));
        jButton53.setFont(new java.awt.Font("Traditional Arabic", 1, 36)); // NOI18N
        jButton53.setForeground(new java.awt.Color(255, 255, 255));
        jButton53.setText("53");
        jButton53.setFocusPainted(false);
        jButton53.setFocusable(false);
        jButton53.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jButton53AncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jButton53.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton53ActionPerformed(evt);
            }
        });
        hardPanel.add(jButton53, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 475, 100, 100));

        jButton54.setBackground(new java.awt.Color(255, 102, 0));
        jButton54.setFont(new java.awt.Font("Traditional Arabic", 1, 36)); // NOI18N
        jButton54.setForeground(new java.awt.Color(255, 255, 255));
        jButton54.setText("54");
        jButton54.setFocusPainted(false);
        jButton54.setFocusable(false);
        jButton54.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jButton54AncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jButton54.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton54ActionPerformed(evt);
            }
        });
        hardPanel.add(jButton54, new org.netbeans.lib.awtextra.AbsoluteConstraints(265, 475, 100, 100));

        jButton55.setBackground(new java.awt.Color(255, 102, 0));
        jButton55.setFont(new java.awt.Font("Traditional Arabic", 1, 36)); // NOI18N
        jButton55.setForeground(new java.awt.Color(255, 255, 255));
        jButton55.setText("55");
        jButton55.setFocusPainted(false);
        jButton55.setFocusable(false);
        jButton55.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jButton55AncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jButton55.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton55ActionPerformed(evt);
            }
        });
        hardPanel.add(jButton55, new org.netbeans.lib.awtextra.AbsoluteConstraints(415, 475, 100, 100));

        jButton56.setBackground(new java.awt.Color(255, 102, 0));
        jButton56.setFont(new java.awt.Font("Traditional Arabic", 1, 36)); // NOI18N
        jButton56.setForeground(new java.awt.Color(255, 255, 255));
        jButton56.setText("56");
        jButton56.setFocusPainted(false);
        jButton56.setFocusable(false);
        jButton56.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jButton56AncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jButton56.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton56ActionPerformed(evt);
            }
        });
        hardPanel.add(jButton56, new org.netbeans.lib.awtextra.AbsoluteConstraints(565, 475, 100, 100));

        jButton57.setBackground(new java.awt.Color(255, 102, 0));
        jButton57.setFont(new java.awt.Font("Traditional Arabic", 1, 36)); // NOI18N
        jButton57.setForeground(new java.awt.Color(255, 255, 255));
        jButton57.setText("57");
        jButton57.setFocusPainted(false);
        jButton57.setFocusable(false);
        jButton57.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jButton57AncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jButton57.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton57ActionPerformed(evt);
            }
        });
        hardPanel.add(jButton57, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 600, 100, 100));

        jButton58.setBackground(new java.awt.Color(255, 102, 0));
        jButton58.setFont(new java.awt.Font("Traditional Arabic", 1, 36)); // NOI18N
        jButton58.setForeground(new java.awt.Color(255, 255, 255));
        jButton58.setText("58");
        jButton58.setFocusPainted(false);
        jButton58.setFocusable(false);
        jButton58.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jButton58AncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jButton58.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton58ActionPerformed(evt);
            }
        });
        hardPanel.add(jButton58, new org.netbeans.lib.awtextra.AbsoluteConstraints(265, 600, 100, 100));

        jButton59.setBackground(new java.awt.Color(255, 102, 0));
        jButton59.setFont(new java.awt.Font("Traditional Arabic", 1, 36)); // NOI18N
        jButton59.setForeground(new java.awt.Color(255, 255, 255));
        jButton59.setText("59");
        jButton59.setFocusPainted(false);
        jButton59.setFocusable(false);
        jButton59.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jButton59AncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jButton59.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton59ActionPerformed(evt);
            }
        });
        hardPanel.add(jButton59, new org.netbeans.lib.awtextra.AbsoluteConstraints(415, 600, 100, 100));

        jButton60.setBackground(new java.awt.Color(255, 102, 0));
        jButton60.setFont(new java.awt.Font("Traditional Arabic", 1, 36)); // NOI18N
        jButton60.setForeground(new java.awt.Color(255, 255, 255));
        jButton60.setText("60");
        jButton60.setFocusPainted(false);
        jButton60.setFocusable(false);
        jButton60.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jButton60AncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jButton60.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton60ActionPerformed(evt);
            }
        });
        hardPanel.add(jButton60, new org.netbeans.lib.awtextra.AbsoluteConstraints(565, 600, 100, 100));

        backBtn.setBackground(new java.awt.Color(255, 255, 0));
        backBtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        backBtn.setForeground(new java.awt.Color(255, 255, 255));
        backBtn.setText("Back");
        backBtn.setFocusPainted(false);
        backBtn.setFocusable(false);
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });
        hardPanel.add(backBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 740, -1, -1));

        getContentPane().add(hardPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 800));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton60ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton60ActionPerformed
        // TODO add your handling code here:
       qui=false;
        if(inter==false)
        {
           new Sokoban(60);
           inter=true;
        }
        else
        {
            
            level.display_level(player_level);
            counter_win=0;
        }
        this.setVisible(false);
    }//GEN-LAST:event_jButton60ActionPerformed

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
                   // TODO add your handling code here:
                    new levelMenu().setVisible(true);
                    this.setVisible(false);
    }//GEN-LAST:event_backBtnActionPerformed

    private void jButton41AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jButton41AncestorAdded
        // TODO add your handling code here:
        if(levels_open[41]==1){
            
        jButton41.setBackground(new java.awt.Color(0, 102, 0));
         }
    }//GEN-LAST:event_jButton41AncestorAdded

    private void jButton42AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jButton42AncestorAdded
        // TODO add your handling code here:
        if (levels_open[42]==1){
            jButton42.setBackground(new java.awt.Color(0, 102, 0));
             }
    }//GEN-LAST:event_jButton42AncestorAdded

    private void jButton43AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jButton43AncestorAdded
        // TODO add your handling code here:
        if(levels_open[43]==1){
            jButton43.setBackground(new java.awt.Color(0, 102, 0));
               
        }
    }//GEN-LAST:event_jButton43AncestorAdded

    private void jButton44AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jButton44AncestorAdded
        // TODO add your handling code here:
        if(levels_open[44]==1){
            jButton44.setBackground(new java.awt.Color(0, 102, 0));
            }
    }//GEN-LAST:event_jButton44AncestorAdded

    private void jButton45AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jButton45AncestorAdded
        // TODO add your handling code here:
        if(levels_open[45]==1){
            
            jButton45.setBackground(new java.awt.Color(0, 102, 0));
            }
    }//GEN-LAST:event_jButton45AncestorAdded

    private void jButton46AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jButton46AncestorAdded
        // TODO add your handling code here:
         if(levels_open[46]==1){
             
            jButton46.setBackground(new java.awt.Color(0, 102, 0));
              }  
    }//GEN-LAST:event_jButton46AncestorAdded

    private void jButton47AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jButton47AncestorAdded
        // TODO add your handling code here:
          if(levels_open[47]==1){
            jButton47.setBackground(new java.awt.Color(0, 102, 0));  
            }  
    }//GEN-LAST:event_jButton47AncestorAdded

    private void jButton48AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jButton48AncestorAdded
        // TODO add your handling code here:
          if(levels_open[48]==1){
            
            jButton48.setBackground(new java.awt.Color(0, 102, 0));
            }
    }//GEN-LAST:event_jButton48AncestorAdded

    private void jButton49AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jButton49AncestorAdded
        // TODO add your handling code here:
          if(levels_open[49]==1){
            
            jButton49.setBackground(new java.awt.Color(0, 102, 0));
            }
    }//GEN-LAST:event_jButton49AncestorAdded

    private void jButton50AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jButton50AncestorAdded
        // TODO add your handling code here:
          if(levels_open[50]==1){
              
            jButton50.setBackground(new java.awt.Color(0, 102, 0));
            }
    }//GEN-LAST:event_jButton50AncestorAdded

    private void jButton51AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jButton51AncestorAdded
        // TODO add your handling code here:
          if(levels_open[51]==1){
           
            jButton51.setBackground(new java.awt.Color(0, 102, 0));
            }
    }//GEN-LAST:event_jButton51AncestorAdded

    private void jButton52AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jButton52AncestorAdded
        // TODO add your handling code here:
          if(levels_open[52]==1){

            jButton52.setBackground(new java.awt.Color(0, 102, 0)); 
            }
    }//GEN-LAST:event_jButton52AncestorAdded

    private void jButton53AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jButton53AncestorAdded
        // TODO add your handling code here:
          if(levels_open[53]==1){
             
            jButton53.setBackground(new java.awt.Color(0, 102, 0));
            }
    }//GEN-LAST:event_jButton53AncestorAdded

    private void jButton54AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jButton54AncestorAdded
        // TODO add your handling code here:
          if(levels_open[54]==1){
            
            jButton54.setBackground(new java.awt.Color(0, 102, 0)); 
            }
    }//GEN-LAST:event_jButton54AncestorAdded

    private void jButton55AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jButton55AncestorAdded
        // TODO add your handling code here:
          if(levels_open[55]==1){
               
            jButton55.setBackground(new java.awt.Color(0, 102, 0)); 
            }
    }//GEN-LAST:event_jButton55AncestorAdded

    private void jButton56AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jButton56AncestorAdded
        // TODO add your handling code here:
                 if(levels_open[56]==1){
            
            jButton56.setBackground(new java.awt.Color(0, 102, 0)); 
            }
    }//GEN-LAST:event_jButton56AncestorAdded

    private void jButton57AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jButton57AncestorAdded
        // TODO add your handling code here:
                    if(levels_open[57]==1){
         jButton57.setBackground(new java.awt.Color(0, 102, 0)); 
            }
    }//GEN-LAST:event_jButton57AncestorAdded

    private void jButton58AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jButton58AncestorAdded
        // TODO add your handling code here:
                    if(levels_open[58]==1){
            jButton58.setBackground(new java.awt.Color(0, 102, 0)); 
            }
    }//GEN-LAST:event_jButton58AncestorAdded

    private void jButton59AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jButton59AncestorAdded
        // TODO add your handling code here:
                    if(levels_open[59]==1){
            jButton59.setBackground(new java.awt.Color(0, 102, 0));             
            }
    }//GEN-LAST:event_jButton59AncestorAdded

    private void jButton60AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jButton60AncestorAdded
        // TODO add your handling code here:
                      if(levels_open[60]==1){
            jButton60.setBackground(new java.awt.Color(0, 102, 0));                
            }
    }//GEN-LAST:event_jButton60AncestorAdded

    private void jButton41ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton41ActionPerformed
        // TODO add your handling code here:
        qui=false;
        if(inter==false)
        {
           new Sokoban(41);
           inter=true;
        }
        else
        {
            
            level.display_level(player_level);
            counter_win=0;
        }
        this.setVisible(false);
    }//GEN-LAST:event_jButton41ActionPerformed

    private void jButton42ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton42ActionPerformed
        // TODO add your handling code here:
        qui=false;
        if(inter==false)
        {
           new Sokoban(42);
           inter=true;
        }
        else
        {
            
            level.display_level(player_level);
            counter_win=0;
        }
        this.setVisible(false);
    }//GEN-LAST:event_jButton42ActionPerformed

    private void jButton43ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton43ActionPerformed
        // TODO add your handling code here:
        qui=false;
        if(inter==false)
        {
           new Sokoban(43);
           inter=true;
        }
        else
        {
            
            level.display_level(player_level);
            counter_win=0;
        }
        this.setVisible(false);
    }//GEN-LAST:event_jButton43ActionPerformed

    private void jButton44ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton44ActionPerformed
        // TODO add your handling code here:
        qui=false;
        if(inter==false)
        {
           new Sokoban(44);
           inter=true;
        }
        else
        {
            
            level.display_level(player_level);
            counter_win=0;
        }
        this.setVisible(false);
    }//GEN-LAST:event_jButton44ActionPerformed

    private void jButton45ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton45ActionPerformed
        // TODO add your handling code here:
        qui=false;
        if(inter==false)
        {
           new Sokoban(45);
           inter=true;
        }
        else
        {
            
            level.display_level(player_level);
            counter_win=0;
        }
        this.setVisible(false);
    }//GEN-LAST:event_jButton45ActionPerformed

    private void jButton46ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton46ActionPerformed
        // TODO add your handling code here:
        qui=false;
        if(inter==false)
        {
           new Sokoban(46);
           inter=true;
        }
        else
        {
            
            level.display_level(player_level);
            counter_win=0;
        }
        this.setVisible(false);
    }//GEN-LAST:event_jButton46ActionPerformed

    private void jButton47ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton47ActionPerformed
        // TODO add your handling code here:
        qui=false;
        if(inter==false)
        {
           new Sokoban(47);
           inter=true;
        }
        else
        {
            
            level.display_level(player_level);
            counter_win=0;
        }
        this.setVisible(false);
    }//GEN-LAST:event_jButton47ActionPerformed

    private void jButton48ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton48ActionPerformed
        // TODO add your handling code here:
        qui=false;
        if(inter==false)
        {
           new Sokoban(48);
           inter=true;
        }
        else
        {
            
            level.display_level(player_level);
            counter_win=0;
        }
        this.setVisible(false);
    }//GEN-LAST:event_jButton48ActionPerformed

    private void jButton49ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton49ActionPerformed
        // TODO add your handling code here:
       qui=false;
        if(inter==false)
        {
           new Sokoban(49);
           inter=true;
        }
        else
        {
            
            level.display_level(player_level);
            counter_win=0;
        }
        this.setVisible(false);
    }//GEN-LAST:event_jButton49ActionPerformed

    private void jButton50ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton50ActionPerformed
        // TODO add your handling code here:
        qui=false;
        if(inter==false)
        {
           new Sokoban(50);
           inter=true;
        }
        else
        {
            
            level.display_level(player_level);
            counter_win=0;
        }
        this.setVisible(false);
    }//GEN-LAST:event_jButton50ActionPerformed

    private void jButton51ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton51ActionPerformed
        // TODO add your handling code here:
        qui=false;
        if(inter==false)
        {
           new Sokoban(51);
           inter=true;
        }
        else
        {
            
            level.display_level(player_level);
            counter_win=0;
        }
        this.setVisible(false);
    }//GEN-LAST:event_jButton51ActionPerformed

    private void jButton52ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton52ActionPerformed
        // TODO add your handling code here:
        qui=false;
        if(inter==false)
        {
           new Sokoban(52);
           inter=true;
        }
        else
        {
            
            level.display_level(player_level);
            counter_win=0;
        }
        this.setVisible(false);
        
    }//GEN-LAST:event_jButton52ActionPerformed

    private void jButton53ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton53ActionPerformed
        // TODO add your handling code here:
        qui=false;
        if(inter==false)
        {
           new Sokoban(53);
           inter=true;
        }
        else
        {
            
            level.display_level(player_level);
            counter_win=0;
        }
        this.setVisible(false);
    }//GEN-LAST:event_jButton53ActionPerformed

    private void jButton54ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton54ActionPerformed
        // TODO add your handling code here:
        qui=false;
        if(inter==false)
        {
           new Sokoban(54);
           inter=true;
        }
        else
        {
            
            level.display_level(player_level);
            counter_win=0;
        }
        this.setVisible(false);
    }//GEN-LAST:event_jButton54ActionPerformed

    private void jButton55ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton55ActionPerformed
        // TODO add your handling code here:
        qui=false;
        if(inter==false)
        {
           new Sokoban(55);
           inter=true;
        }
        else
        {
            
            level.display_level(player_level);
            counter_win=0;
        }
        this.setVisible(false);
    }//GEN-LAST:event_jButton55ActionPerformed

    private void jButton56ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton56ActionPerformed
        // TODO add your handling code here:
        qui=false;
        if(inter==false)
        {
           new Sokoban(56);
           inter=true;
        }
        else
        {
            
            level.display_level(player_level);
            counter_win=0;
        }
        this.setVisible(false);
    }//GEN-LAST:event_jButton56ActionPerformed

    private void jButton57ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton57ActionPerformed
        // TODO add your handling code here:
        qui=false;
        if(inter==false)
        {
           new Sokoban(57);
           inter=true;
        }
        else
        {
            
            level.display_level(player_level);
            counter_win=0;
        }
        this.setVisible(false);
    }//GEN-LAST:event_jButton57ActionPerformed

    private void jButton58ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton58ActionPerformed
        // TODO add your handling code here:
        qui=false;
        if(inter==false)
        {
           new Sokoban(58);
           inter=true;
        }
        else
        {
            
            level.display_level(player_level);
            counter_win=0;
        }
        this.setVisible(false);
    }//GEN-LAST:event_jButton58ActionPerformed

    private void jButton59ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton59ActionPerformed
        // TODO add your handling code here:
        qui=false;
        if(inter==false)
        {
           new Sokoban(59);
           inter=true;
        }
        else
        {
            
            level.display_level(player_level);
            counter_win=0;
        }
        this.setVisible(false);
    }//GEN-LAST:event_jButton59ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(hardMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(hardMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(hardMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(hardMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new hardMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBtn;
    private javax.swing.JPanel hardPanel;
    private javax.swing.JButton jButton41;
    private javax.swing.JButton jButton42;
    private javax.swing.JButton jButton43;
    private javax.swing.JButton jButton44;
    private javax.swing.JButton jButton45;
    private javax.swing.JButton jButton46;
    private javax.swing.JButton jButton47;
    private javax.swing.JButton jButton48;
    private javax.swing.JButton jButton49;
    private javax.swing.JButton jButton50;
    private javax.swing.JButton jButton51;
    private javax.swing.JButton jButton52;
    private javax.swing.JButton jButton53;
    private javax.swing.JButton jButton54;
    private javax.swing.JButton jButton55;
    private javax.swing.JButton jButton56;
    private javax.swing.JButton jButton57;
    private javax.swing.JButton jButton58;
    private javax.swing.JButton jButton59;
    private javax.swing.JButton jButton60;
    // End of variables declaration//GEN-END:variables
}
