/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sokoban;
import static sokoban.homeForm.qui;
/**
 *
 * @author Win10
 */
public class levelMenu extends javax.swing.JFrame {

    /**
     * Creates new form levelMenu
     */
    public levelMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        levelPanel = new javax.swing.JPanel();
        easyBtn = new javax.swing.JButton();
        madiumBtn = new javax.swing.JButton();
        hardBtn = new javax.swing.JButton();
        backBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SOKOBAN");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        levelPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        easyBtn.setBackground(new java.awt.Color(255, 255, 0));
        easyBtn.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        easyBtn.setForeground(new java.awt.Color(255, 255, 255));
        easyBtn.setText("Easy");
        easyBtn.setFocusPainted(false);
        easyBtn.setFocusable(false);
        easyBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                easyBtnActionPerformed(evt);
            }
        });
        levelPanel.add(easyBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 340, 150, 60));

        madiumBtn.setBackground(new java.awt.Color(255, 255, 0));
        madiumBtn.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        madiumBtn.setForeground(new java.awt.Color(255, 255, 255));
        madiumBtn.setText("Medium");
        madiumBtn.setFocusPainted(false);
        madiumBtn.setFocusable(false);
        madiumBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                madiumBtnActionPerformed(evt);
            }
        });
        levelPanel.add(madiumBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 450, 150, 60));

        hardBtn.setBackground(new java.awt.Color(255, 255, 0));
        hardBtn.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        hardBtn.setForeground(new java.awt.Color(255, 255, 255));
        hardBtn.setText("Hard");
        hardBtn.setFocusPainted(false);
        hardBtn.setFocusable(false);
        hardBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hardBtnActionPerformed(evt);
            }
        });
        levelPanel.add(hardBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 560, 150, 60));

        backBtn.setBackground(new java.awt.Color(255, 255, 0));
        backBtn.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        backBtn.setForeground(new java.awt.Color(255, 255, 255));
        backBtn.setText("Back");
        backBtn.setFocusPainted(false);
        backBtn.setFocusable(false);
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });
        levelPanel.add(backBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 630, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sokoban/unnamed.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        jLabel1.setMaximumSize(new java.awt.Dimension(800, 800));
        levelPanel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 800));

        getContentPane().add(levelPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 800));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void easyBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_easyBtnActionPerformed
        // TODO add your handling code here:
       
        this.setVisible(false);
       new player_levels().setVisible(true);
    }//GEN-LAST:event_easyBtnActionPerformed

    private void madiumBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_madiumBtnActionPerformed
        // TODO add your handling code here:
         this.setVisible(false);
         new mediumMenu().setVisible(true);
        
    }//GEN-LAST:event_madiumBtnActionPerformed

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        // TODO add your handling code here:
         new mainMenu().setVisible(true);
         this.setVisible(false);
    }//GEN-LAST:event_backBtnActionPerformed

    private void hardBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hardBtnActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new hardMenu().setVisible(true);
    }//GEN-LAST:event_hardBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(levelMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(levelMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(levelMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(levelMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new levelMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBtn;
    private javax.swing.JButton easyBtn;
    private javax.swing.JButton hardBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel levelPanel;
    private javax.swing.JButton madiumBtn;
    // End of variables declaration//GEN-END:variables
}
