/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sokoban;

import static sokoban.Sokoban.player_level;
import static sokoban.Sokoban.level;
import static sokoban.Sokoban.inter;
import static sokoban.Sokoban.counter_win;
import static sokoban.homeForm.qui;
import static sokoban.Sokoban.levels_open;
/**
 *
 * @author Win10
 */
public class mediumMenu extends javax.swing.JFrame {

    
    /**
     * Creates new form mediumMenu
     */
    public mediumMenu() {
        initComponents();
    }
    
    
    
    
    public int getplayer_Level(){
        return player_level;
    }
    
    public void setplayer_level(int level)
    {
        player_level=level;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mediumPanel = new javax.swing.JPanel();
        jButton40 = new javax.swing.JButton();
        jButton21 = new javax.swing.JButton();
        jButton22 = new javax.swing.JButton();
        jButton23 = new javax.swing.JButton();
        jButton24 = new javax.swing.JButton();
        jButton25 = new javax.swing.JButton();
        jButton26 = new javax.swing.JButton();
        jButton27 = new javax.swing.JButton();
        jButton28 = new javax.swing.JButton();
        jButton29 = new javax.swing.JButton();
        jButton30 = new javax.swing.JButton();
        jButton31 = new javax.swing.JButton();
        jButton32 = new javax.swing.JButton();
        jButton33 = new javax.swing.JButton();
        jButton34 = new javax.swing.JButton();
        jButton35 = new javax.swing.JButton();
        jButton36 = new javax.swing.JButton();
        jButton37 = new javax.swing.JButton();
        jButton38 = new javax.swing.JButton();
        jButton39 = new javax.swing.JButton();
        backBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SOKOBAN");
        setName("mediumFrame"); // NOI18N
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        mediumPanel.setBackground(new java.awt.Color(0, 153, 255));
        mediumPanel.setForeground(new java.awt.Color(255, 255, 255));
        mediumPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton40.setBackground(new java.awt.Color(255, 102, 0));
        jButton40.setFont(new java.awt.Font("Traditional Arabic", 1, 36)); // NOI18N
        jButton40.setForeground(new java.awt.Color(255, 255, 255));
        jButton40.setText("40");
        jButton40.setFocusPainted(false);
        jButton40.setFocusable(false);
        jButton40.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jButton40AncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jButton40.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton40ActionPerformed(evt);
            }
        });
        mediumPanel.add(jButton40, new org.netbeans.lib.awtextra.AbsoluteConstraints(565, 600, 100, 100));

        jButton21.setBackground(new java.awt.Color(255, 102, 51));
        jButton21.setFont(new java.awt.Font("Traditional Arabic", 1, 36)); // NOI18N
        jButton21.setForeground(new java.awt.Color(255, 255, 255));
        jButton21.setText("21");
        jButton21.setFocusPainted(false);
        jButton21.setFocusable(false);
        jButton21.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jButton21AncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jButton21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton21ActionPerformed(evt);
            }
        });
        mediumPanel.add(jButton21, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 100, 100, 100));

        jButton22.setBackground(new java.awt.Color(255, 102, 51));
        jButton22.setFont(new java.awt.Font("Traditional Arabic", 1, 36)); // NOI18N
        jButton22.setForeground(new java.awt.Color(255, 255, 255));
        jButton22.setText("22");
        jButton22.setFocusable(false);
        jButton22.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jButton22AncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jButton22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton22ActionPerformed(evt);
            }
        });
        mediumPanel.add(jButton22, new org.netbeans.lib.awtextra.AbsoluteConstraints(265, 100, 100, 100));

        jButton23.setBackground(new java.awt.Color(255, 102, 51));
        jButton23.setFont(new java.awt.Font("Traditional Arabic", 1, 36)); // NOI18N
        jButton23.setForeground(new java.awt.Color(255, 255, 255));
        jButton23.setText("23");
        jButton23.setFocusable(false);
        jButton23.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jButton23AncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jButton23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton23ActionPerformed(evt);
            }
        });
        mediumPanel.add(jButton23, new org.netbeans.lib.awtextra.AbsoluteConstraints(415, 100, 100, 100));

        jButton24.setBackground(new java.awt.Color(255, 102, 0));
        jButton24.setFont(new java.awt.Font("Traditional Arabic", 1, 36)); // NOI18N
        jButton24.setForeground(new java.awt.Color(255, 255, 255));
        jButton24.setText("24");
        jButton24.setFocusable(false);
        jButton24.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jButton24AncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jButton24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton24ActionPerformed(evt);
            }
        });
        mediumPanel.add(jButton24, new org.netbeans.lib.awtextra.AbsoluteConstraints(565, 100, 100, 100));

        jButton25.setBackground(new java.awt.Color(255, 102, 0));
        jButton25.setFont(new java.awt.Font("Traditional Arabic", 1, 36)); // NOI18N
        jButton25.setForeground(new java.awt.Color(255, 255, 255));
        jButton25.setText("25");
        jButton25.setFocusPainted(false);
        jButton25.setFocusable(false);
        jButton25.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jButton25AncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jButton25.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton25ActionPerformed(evt);
            }
        });
        mediumPanel.add(jButton25, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 225, 100, 100));

        jButton26.setBackground(new java.awt.Color(255, 102, 0));
        jButton26.setFont(new java.awt.Font("Traditional Arabic", 1, 36)); // NOI18N
        jButton26.setForeground(new java.awt.Color(255, 255, 255));
        jButton26.setText("26");
        jButton26.setFocusPainted(false);
        jButton26.setFocusable(false);
        jButton26.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jButton26AncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jButton26.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton26ActionPerformed(evt);
            }
        });
        mediumPanel.add(jButton26, new org.netbeans.lib.awtextra.AbsoluteConstraints(265, 225, 100, 100));

        jButton27.setBackground(new java.awt.Color(255, 102, 0));
        jButton27.setFont(new java.awt.Font("Traditional Arabic", 1, 36)); // NOI18N
        jButton27.setForeground(new java.awt.Color(255, 255, 255));
        jButton27.setText("27");
        jButton27.setFocusPainted(false);
        jButton27.setFocusable(false);
        jButton27.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jButton27AncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jButton27.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton27ActionPerformed(evt);
            }
        });
        mediumPanel.add(jButton27, new org.netbeans.lib.awtextra.AbsoluteConstraints(415, 225, 100, 100));

        jButton28.setBackground(new java.awt.Color(255, 102, 0));
        jButton28.setFont(new java.awt.Font("Traditional Arabic", 1, 36)); // NOI18N
        jButton28.setForeground(new java.awt.Color(255, 255, 255));
        jButton28.setText("28");
        jButton28.setFocusPainted(false);
        jButton28.setFocusable(false);
        jButton28.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jButton28AncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jButton28.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton28ActionPerformed(evt);
            }
        });
        mediumPanel.add(jButton28, new org.netbeans.lib.awtextra.AbsoluteConstraints(565, 225, 100, 100));

        jButton29.setBackground(new java.awt.Color(255, 102, 0));
        jButton29.setFont(new java.awt.Font("Traditional Arabic", 1, 36)); // NOI18N
        jButton29.setForeground(new java.awt.Color(255, 255, 255));
        jButton29.setText("29");
        jButton29.setFocusPainted(false);
        jButton29.setFocusable(false);
        jButton29.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jButton29AncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jButton29.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton29ActionPerformed(evt);
            }
        });
        mediumPanel.add(jButton29, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 350, 100, 100));

        jButton30.setBackground(new java.awt.Color(255, 102, 0));
        jButton30.setFont(new java.awt.Font("Traditional Arabic", 1, 36)); // NOI18N
        jButton30.setForeground(new java.awt.Color(255, 255, 255));
        jButton30.setText("30");
        jButton30.setFocusPainted(false);
        jButton30.setFocusable(false);
        jButton30.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jButton30AncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jButton30.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton30ActionPerformed(evt);
            }
        });
        mediumPanel.add(jButton30, new org.netbeans.lib.awtextra.AbsoluteConstraints(265, 350, 100, 100));

        jButton31.setBackground(new java.awt.Color(255, 102, 0));
        jButton31.setFont(new java.awt.Font("Traditional Arabic", 1, 36)); // NOI18N
        jButton31.setForeground(new java.awt.Color(255, 255, 255));
        jButton31.setText("31");
        jButton31.setFocusPainted(false);
        jButton31.setFocusable(false);
        jButton31.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jButton31AncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jButton31.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton31ActionPerformed(evt);
            }
        });
        mediumPanel.add(jButton31, new org.netbeans.lib.awtextra.AbsoluteConstraints(415, 350, 100, 100));

        jButton32.setBackground(new java.awt.Color(255, 102, 0));
        jButton32.setFont(new java.awt.Font("Traditional Arabic", 1, 36)); // NOI18N
        jButton32.setForeground(new java.awt.Color(255, 255, 255));
        jButton32.setText("32");
        jButton32.setFocusPainted(false);
        jButton32.setFocusable(false);
        jButton32.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jButton32AncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jButton32.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton32ActionPerformed(evt);
            }
        });
        mediumPanel.add(jButton32, new org.netbeans.lib.awtextra.AbsoluteConstraints(565, 350, 100, 100));

        jButton33.setBackground(new java.awt.Color(255, 102, 0));
        jButton33.setFont(new java.awt.Font("Traditional Arabic", 1, 36)); // NOI18N
        jButton33.setForeground(new java.awt.Color(255, 255, 255));
        jButton33.setText("33");
        jButton33.setFocusPainted(false);
        jButton33.setFocusable(false);
        jButton33.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jButton33AncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jButton33.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton33ActionPerformed(evt);
            }
        });
        mediumPanel.add(jButton33, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 475, 100, 100));

        jButton34.setBackground(new java.awt.Color(255, 102, 0));
        jButton34.setFont(new java.awt.Font("Traditional Arabic", 1, 36)); // NOI18N
        jButton34.setForeground(new java.awt.Color(255, 255, 255));
        jButton34.setText("34");
        jButton34.setFocusPainted(false);
        jButton34.setFocusable(false);
        jButton34.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jButton34AncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jButton34.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton34ActionPerformed(evt);
            }
        });
        mediumPanel.add(jButton34, new org.netbeans.lib.awtextra.AbsoluteConstraints(265, 475, 100, 100));

        jButton35.setBackground(new java.awt.Color(255, 102, 0));
        jButton35.setFont(new java.awt.Font("Traditional Arabic", 1, 36)); // NOI18N
        jButton35.setForeground(new java.awt.Color(255, 255, 255));
        jButton35.setText("35");
        jButton35.setFocusPainted(false);
        jButton35.setFocusable(false);
        jButton35.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jButton35AncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jButton35.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton35ActionPerformed(evt);
            }
        });
        mediumPanel.add(jButton35, new org.netbeans.lib.awtextra.AbsoluteConstraints(415, 475, 100, 100));

        jButton36.setBackground(new java.awt.Color(255, 102, 0));
        jButton36.setFont(new java.awt.Font("Traditional Arabic", 1, 36)); // NOI18N
        jButton36.setForeground(new java.awt.Color(255, 255, 255));
        jButton36.setText("36");
        jButton36.setFocusPainted(false);
        jButton36.setFocusable(false);
        jButton36.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jButton36AncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jButton36.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton36ActionPerformed(evt);
            }
        });
        mediumPanel.add(jButton36, new org.netbeans.lib.awtextra.AbsoluteConstraints(565, 475, 100, 100));

        jButton37.setBackground(new java.awt.Color(255, 102, 0));
        jButton37.setFont(new java.awt.Font("Traditional Arabic", 1, 36)); // NOI18N
        jButton37.setForeground(new java.awt.Color(255, 255, 255));
        jButton37.setText("37");
        jButton37.setFocusPainted(false);
        jButton37.setFocusable(false);
        jButton37.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jButton37AncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jButton37.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton37ActionPerformed(evt);
            }
        });
        mediumPanel.add(jButton37, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 600, 100, 100));

        jButton38.setBackground(new java.awt.Color(255, 102, 0));
        jButton38.setFont(new java.awt.Font("Traditional Arabic", 1, 36)); // NOI18N
        jButton38.setForeground(new java.awt.Color(255, 255, 255));
        jButton38.setText("38");
        jButton38.setFocusPainted(false);
        jButton38.setFocusable(false);
        jButton38.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jButton38AncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jButton38.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton38ActionPerformed(evt);
            }
        });
        mediumPanel.add(jButton38, new org.netbeans.lib.awtextra.AbsoluteConstraints(265, 600, 100, 100));

        jButton39.setBackground(new java.awt.Color(255, 102, 0));
        jButton39.setFont(new java.awt.Font("Traditional Arabic", 1, 36)); // NOI18N
        jButton39.setForeground(new java.awt.Color(255, 255, 255));
        jButton39.setText("39");
        jButton39.setFocusPainted(false);
        jButton39.setFocusable(false);
        jButton39.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jButton39AncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jButton39.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton39ActionPerformed(evt);
            }
        });
        mediumPanel.add(jButton39, new org.netbeans.lib.awtextra.AbsoluteConstraints(415, 600, 100, 100));

        backBtn.setBackground(new java.awt.Color(255, 255, 0));
        backBtn.setFont(new java.awt.Font("Traditional Arabic", 1, 18)); // NOI18N
        backBtn.setForeground(new java.awt.Color(255, 255, 255));
        backBtn.setText("Back");
        backBtn.setFocusPainted(false);
        backBtn.setFocusable(false);
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });
        mediumPanel.add(backBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 740, -1, 30));

        getContentPane().add(mediumPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 800));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton40ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton40ActionPerformed
        // TODO add your handling code here:
        qui=false;
        if(inter==false)
        {
           new Sokoban(40);
           inter=true;
        }
        else
        {
            
            level.display_level(player_level);
            counter_win=0;
        }
        this.setVisible(false);
         
    }//GEN-LAST:event_jButton40ActionPerformed

    private void jButton22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton22ActionPerformed
        // TODO add your handling code here:
        qui=false;
       if(inter==false)
        {
           new Sokoban(22);
           inter=true;
        }
        else
        {
            
            level.display_level(player_level);
            counter_win=0;
        }
        this.setVisible(false);
    }//GEN-LAST:event_jButton22ActionPerformed

    private void jButton23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton23ActionPerformed
        // TODO add your handling code here:
        qui=false;
       if(inter==false)
        {
           new Sokoban(32);
           inter=true;
        }
        else
        {
            
            level.display_level(player_level);
            counter_win=0;
        }
        this.setVisible(false);
    }//GEN-LAST:event_jButton23ActionPerformed

    private void jButton24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton24ActionPerformed
        // TODO add your handling code here:
        qui=false;
        if(inter==false)
        {
           new Sokoban(24);
           inter=true;
        }
        else
        {
            
            level.display_level(player_level);
            counter_win=0;
        }
        this.setVisible(false);
    }//GEN-LAST:event_jButton24ActionPerformed

    private void jButton25ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton25ActionPerformed
        // TODO add your handling code here:
        qui=false;
        if(inter==false)
        {
           new Sokoban(25);
           inter=true;
        }
        else
        {
            
            level.display_level(player_level);
            counter_win=0;
        }
        this.setVisible(false);
    }//GEN-LAST:event_jButton25ActionPerformed

    private void jButton26ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton26ActionPerformed
        // TODO add your handling code here:
        qui=false;
        if(inter==false)
        {
           new Sokoban(26);
           inter=true;
        }
        else
        {
            
            level.display_level(player_level);
            counter_win=0;
        }
        this.setVisible(false);
    }//GEN-LAST:event_jButton26ActionPerformed

    private void jButton27ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton27ActionPerformed
        // TODO add your handling code here:
        qui=false;
       if(inter==false)
        {
           new Sokoban(27);
           inter=true;
        }
        else
        {
            
            level.display_level(player_level);
            counter_win=0;
        }
        this.setVisible(false);
    }//GEN-LAST:event_jButton27ActionPerformed

    private void jButton28ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton28ActionPerformed
        // TODO add your handling code here:
        qui=false;
        if(inter==false)
        {
           new Sokoban(28);
           inter=true;
        }
        else
        {
            
            level.display_level(player_level);
            counter_win=0;
        }
        this.setVisible(false);
    }//GEN-LAST:event_jButton28ActionPerformed

    private void jButton29ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton29ActionPerformed
        // TODO add your handling code here:
        qui=false;
        if(inter==false)
        {
           new Sokoban(29);
           inter=true;
        }
        else
        {
            
            level.display_level(player_level);
            counter_win=0;
        }
        this.setVisible(false);
    }//GEN-LAST:event_jButton29ActionPerformed

    private void jButton30ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton30ActionPerformed
        // TODO add your handling code here:
        qui=false;
       if(inter==false)
        {
           new Sokoban(30);
           inter=true;
        }
        else
        {
            
            level.display_level(player_level);
            counter_win=0;
        }
        this.setVisible(false);
    }//GEN-LAST:event_jButton30ActionPerformed

    private void jButton31ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton31ActionPerformed
        // TODO add your handling code here:
        qui=false;
        if(inter==false)
        {
           new Sokoban(31);
           inter=true;
        }
        else
        {
            
            level.display_level(player_level);
            counter_win=0;
        }
        this.setVisible(false);
    }//GEN-LAST:event_jButton31ActionPerformed

    private void jButton32ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton32ActionPerformed
        // TODO add your handling code here:
        qui=false;
       if(inter==false)
        {
           new Sokoban(32);
           inter=true;
        }
        else
        {
            
            level.display_level(player_level);
            counter_win=0;
        }
        this.setVisible(false);
    }//GEN-LAST:event_jButton32ActionPerformed

    private void jButton33ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton33ActionPerformed
        // TODO add your handling code here:
        qui=false;
        if(inter==false)
        {
           new Sokoban(33);
           inter=true;
        }
        else
        {
            
            level.display_level(player_level);
            counter_win=0;
        }
        this.setVisible(false);
    }//GEN-LAST:event_jButton33ActionPerformed

    private void jButton34ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton34ActionPerformed
        // TODO add your handling code here:
        qui=false;
        if(inter==false)
        {
           new Sokoban(34);
           inter=true;
        }
        else
        {
            
            level.display_level(player_level);
            counter_win=0;
        }
        this.setVisible(false);
    }//GEN-LAST:event_jButton34ActionPerformed

    private void jButton35ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton35ActionPerformed
        // TODO add your handling code here:
        qui=false;
        if(inter==false)
        {
           new Sokoban(35);
           inter=true;
        }
        else
        {
            
            level.display_level(player_level);
            counter_win=0;
        }
        this.setVisible(false);
    }//GEN-LAST:event_jButton35ActionPerformed

    private void jButton36ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton36ActionPerformed
        // TODO add your handling code here:
        qui=false;
       if(inter==false)
        {
           new Sokoban(36);
           inter=true;
        }
        else
        {
            
            level.display_level(player_level);
            counter_win=0;
        }
        this.setVisible(false);
    }//GEN-LAST:event_jButton36ActionPerformed

    private void jButton37ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton37ActionPerformed
        // TODO add your handling code here:
        qui=false;
        if(inter==false)
        {
           new Sokoban(37);
           inter=true;
        }
        else
        {
            
            level.display_level(player_level);
            counter_win=0;
        }
        this.setVisible(false);
    }//GEN-LAST:event_jButton37ActionPerformed

    private void jButton38ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton38ActionPerformed
        // TODO add your handling code here:
        qui=false;
        if(inter==false)
        {
           new Sokoban(38);
           inter=true;
        }
        else
        {
            
            level.display_level(player_level);
            counter_win=0;
        }
        this.setVisible(false);
    }//GEN-LAST:event_jButton38ActionPerformed

    private void jButton39ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton39ActionPerformed
        // TODO add your handling code here:
        qui=false;
       if(inter==false)
        {
           new Sokoban(39);
           inter=true;
        }
        else
        {
            
            level.display_level(player_level);
            counter_win=0;
        }
        this.setVisible(false);
    }//GEN-LAST:event_jButton39ActionPerformed

    private void jButton21AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jButton21AncestorAdded
        // TODO add your handling code here:
        
       if (levels_open[21]==1){
        jButton21.setBackground(new java.awt.Color(0, 102, 0));

        }
    }//GEN-LAST:event_jButton21AncestorAdded

    private void jButton29AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jButton29AncestorAdded
        // TODO add your handling code here:
        if(levels_open[29]==1){
            
        jButton29.setBackground(new java.awt.Color(0, 102, 0));
         }
    }//GEN-LAST:event_jButton29AncestorAdded

    private void jButton22AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jButton22AncestorAdded
        // TODO add your handling code here:
       if (levels_open[22]==1){
       
        jButton22.setBackground(new java.awt.Color(0, 102, 0));
        
        }
    }//GEN-LAST:event_jButton22AncestorAdded

    private void jButton23AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jButton23AncestorAdded
        // TODO add your handling code here:
        if (levels_open[23]==1){
        jButton23.setBackground(new java.awt.Color(0, 102, 0));
       }
    }//GEN-LAST:event_jButton23AncestorAdded

    private void jButton24AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jButton24AncestorAdded
        // TODO add your handling code here:
        if(levels_open[24]==1){
            
        jButton24.setBackground(new java.awt.Color(0, 102, 0));
        }
    }//GEN-LAST:event_jButton24AncestorAdded

    private void jButton25AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jButton25AncestorAdded
        // TODO add your handling code here:
        if(levels_open[25]==1){
            
        jButton25.setBackground(new java.awt.Color(0, 102, 0));
        }
    }//GEN-LAST:event_jButton25AncestorAdded

    private void jButton26AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jButton26AncestorAdded
        // TODO add your handling code here:
        if (levels_open[25]==1){
            
        jButton26.setBackground(new java.awt.Color(0, 102, 0));
       }
    }//GEN-LAST:event_jButton26AncestorAdded

    private void jButton27AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jButton27AncestorAdded
        // TODO add your handling code here:
        if (levels_open[27]==1){
            
        jButton27.setBackground(new java.awt.Color(0, 102, 0));
       
        }
    }//GEN-LAST:event_jButton27AncestorAdded

    private void jButton28AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jButton28AncestorAdded
        // TODO add your handling code here:
        if (levels_open[28]==1){
       
        jButton28.setBackground(new java.awt.Color(0, 102, 0));
       

        }
    }//GEN-LAST:event_jButton28AncestorAdded

    private void jButton30AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jButton30AncestorAdded
        // TODO add your handling code here:
        if (levels_open[30]==1){
           
           jButton30.setBackground(new java.awt.Color(0, 102, 0));
           }
    }//GEN-LAST:event_jButton30AncestorAdded

    private void jButton31AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jButton31AncestorAdded
        // TODO add your handling code here:
                if (levels_open[31]==1){
           
           jButton31.setBackground(new java.awt.Color(0, 102, 0));
           }
    }//GEN-LAST:event_jButton31AncestorAdded

    private void jButton32AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jButton32AncestorAdded
        // TODO add your handling code here
           if (levels_open[32]==1){
           
           jButton32.setBackground(new java.awt.Color(0, 102, 0));
          
        }
    }//GEN-LAST:event_jButton32AncestorAdded

    private void jButton33AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jButton33AncestorAdded
        // TODO add your handling code here:
              if (levels_open[33]==1){
           
           jButton33.setBackground(new java.awt.Color(0, 102, 0));
          
        }
    }//GEN-LAST:event_jButton33AncestorAdded

    private void jButton34AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jButton34AncestorAdded
        // TODO add your handling code here:
                 if (levels_open[34]==1){
           
           jButton34.setBackground(new java.awt.Color(0, 102, 0));
           }
    }//GEN-LAST:event_jButton34AncestorAdded

    private void jButton35AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jButton35AncestorAdded
        // TODO add your handling code here:
           if (levels_open[35]==1){
           
           jButton35.setBackground(new java.awt.Color(0, 102, 0));
            }
    }//GEN-LAST:event_jButton35AncestorAdded

    private void jButton36AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jButton36AncestorAdded
        // TODO add your handling code here:
             if (levels_open[36]==1){
           
           jButton36.setBackground(new java.awt.Color(0, 102, 0));
           }
    }//GEN-LAST:event_jButton36AncestorAdded

    private void jButton37AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jButton37AncestorAdded
        // TODO add your handling code here
         if (levels_open[37]==1){
           
           jButton37.setBackground(new java.awt.Color(0, 102, 0));
            }
    }//GEN-LAST:event_jButton37AncestorAdded

    private void jButton38AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jButton38AncestorAdded
        // TODO add your handling code here:
            if (levels_open[38]==1){
                      
           jButton38.setBackground(new java.awt.Color(0, 102,0)); 
           }

    }//GEN-LAST:event_jButton38AncestorAdded

    private void jButton39AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jButton39AncestorAdded
        // TODO add your handling code here
        if (levels_open[39]==1){
          
           jButton39.setBackground(new java.awt.Color(0, 102,0));           
           }
    }//GEN-LAST:event_jButton39AncestorAdded

    private void jButton40AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jButton40AncestorAdded
//        // TODO add your handling code here:
          if(levels_open[40]==1){
           jButton40.setBackground(new java.awt.Color(0, 102,0));          
           }
        
    }//GEN-LAST:event_jButton40AncestorAdded

    private void jButton21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton21ActionPerformed
        // TODO add your handling code here:
        qui=false;
           if(inter==false)
        {
           new Sokoban(21);
           inter=true;
        }
        else
        {
            
            level.display_level(player_level);
            counter_win=0;
        }
        this.setVisible(false);
          

    }//GEN-LAST:event_jButton21ActionPerformed

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        // TODO add your handling code here:
////        new test().setVisible(true);
             new levelMenu().setVisible(true);
             this.setVisible(false);
    }//GEN-LAST:event_backBtnActionPerformed
       
        
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mediumMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mediumMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mediumMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mediumMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new mediumMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBtn;
    private javax.swing.JButton jButton21;
    private javax.swing.JButton jButton22;
    private javax.swing.JButton jButton23;
    private javax.swing.JButton jButton24;
    private javax.swing.JButton jButton25;
    private javax.swing.JButton jButton26;
    private javax.swing.JButton jButton27;
    private javax.swing.JButton jButton28;
    private javax.swing.JButton jButton29;
    private javax.swing.JButton jButton30;
    private javax.swing.JButton jButton31;
    private javax.swing.JButton jButton32;
    private javax.swing.JButton jButton33;
    private javax.swing.JButton jButton34;
    private javax.swing.JButton jButton35;
    private javax.swing.JButton jButton36;
    private javax.swing.JButton jButton37;
    private javax.swing.JButton jButton38;
    private javax.swing.JButton jButton39;
    private javax.swing.JButton jButton40;
    private javax.swing.JPanel mediumPanel;
    // End of variables declaration//GEN-END:variables
}
